[package]
name = "lab-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "The Lab compiler and its aggregate intermediate representation."

[lib]
name = "lab_compiler"
path = "src/lib.rs"

[[bin]]
name = "labc"
path = "src/bin/labc/main.rs"

[[bin]]
name = "lab-opt"
path = "src/bin/lab-opt/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lab-capability.workspace = true
lab-language.workspace = true
pliron.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.27.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[lints]
workspace = true
