[package]
name = "lab-sbol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "SBOL as a source and target for Lab designs."

[dependencies]
lab-language.workspace = true
sbol3.workspace = true
thiserror.workspace = true

[lints]
workspace = true
