[package]
name = "lab-sdk-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Python bindings for the Lab Compiler."
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
lab-sdk.workspace = true
pyo3.workspace = true
serde_json.workspace = true

[lints]
workspace = true
