def compile_lab_module(source: str) -> str: ...
def analyze_lab_modules(modules: list[tuple[str, str]]) -> str: ...
def lab_standard_library() -> str: ...
def validate_method_definitions(definitions_json: str, include_standard: bool) -> str: ...
def refine_lab_modules(
    modules: list[tuple[str, str]], definitions_json: str, include_standard: bool
) -> str: ...
